---
- hosts: all
  tasks:
    - name:
      debug: msg={{ test_value }}
      when: ansible_os_family == 'Debian'

    - name:
      debug: msg={{ test_user }}
      when: ansible_os_family == 'RedHat'
