---
# tasks file for rabbitmq
  - name: install package
      apt: name={{item}} state=present
      with_items:
        - rabbitmq-server
      when: ansible_os_family == 'Debian'

   - name: add user
     rabbitmq_user:
       user: openstack
       password: openstack    
       permissions: 
         - vhost: /
           configure_priv: .*
           read_priv: .*
           write_priv: .*  
       state: present
